{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: binance-ingress
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: binance-freqbot.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: binance-api-service
            port:
              number: 8200
---
{{- end }}