{{- if (and .Values.bot.enabled .Values.config.api_server.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: binance-api-service
  labels:
    app: binance-freqtrade
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8080
  selector:
    app: binance-freqtrade
{{- end }}